#!/bin/sh
echo "Enter the value of n"
read n
i=0
res=0
while [ $i -le $n ] 
do
    if [ $((i%2)) -eq 0 ]
    then 
        res=$((res+i))
        i=$((i+1))
    else
        i=$((i+1))
    fi
done
echo "$res"
